spring:

  application:
    name: AI image tools

  servlet:
    # File Upload Configuration
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ## Enable Virtual Threads (Requires Spring Boot 3.2+ and Java 21+)
  threads.virtual.enabled: true

server:
  port: 8080



# Gemini API Configuration
gemini:
  api:
    # read from env variable GEMINI_API_KEY
    key: ${GEMINI_API_KEY}
    #key:
  # Ensure this is the correct endpoint for the model you want to use (e.g., gemini-1.5-flash-latest)
    base-url: https://generativelanguage.googleapis.com
    path: /v1beta/models/gemini-1.5-flash-latest:generateContent

# Logging Configuration (Optional)
logging:
  level:
    com.github.billygk.ai.image: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG # Or TRACE for even more detail
    # You might also want to check component scanning
    org.springframework.context.annotation.ClassPathBeanDefinitionScanner: DEBUG
